### ISSUE TITLE
(Lỗi) Source Nettruyen lỗi load ảnh truyện

### ISSUE THREAD

**Issue by ThanhPhuoc91** [hoang3402/extensions-vn#13]
Source Nettruyen có truyện load được ảnh có truyện không load được.

**Comment by hoang3402** [comment]
cho mình tên truyện vs chapter nào với

**Comment by hoang3402** [comment]
mình thấy mấy truyện khác vẫn hoạt động bình thường

**Comment by hoang3402** [comment]
có lẽ lỗi do server nettruyen

**Comment by hoang3402** [comment]
đã fix
